apiVersion: v1
kind: Service
metadata:
  name: simple-server-with-grafana-app
spec:
  selector:
    app: simple-server-with-grafana-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
